### ISSUE TITLE
Deselect Issues

### ISSUE THREAD

**Issue by pvaughn-utah** [ctsit/imagemap#52] opened 2020-10-08 23:45 UTC
I've added the @IMAGEMAP module in my institutional REDCap project. I'm having issues with using @IMAGEMAP=PAINMAP_MALE/FEMALE, where once a body region is selected in the active survey, the respondent cannot unselect if a mistake is made. Have others had this issue? Is there a fix for allowing respondent to deselect or reset?

**Comment by ChemiKyle** [comment] 2020-10-15 15:11
Hi @pvaughn-utah can you tell me which version of REDCap you're running?

**Comment by pvaughn-utah** [comment] 2020-10-15 20:31
My institution is using REDCap version: REDCap 10.3.7

**Comment by pvaughn-utah** [comment] 2020-10-15 20:44
[Body Map Unchecked Issues.pdf](https://github.com/ctsit/imagemap/files/5387654/Body.Map.Unchecked.Issues.pdf)
 Here is an example image of what is happening; when the region is unchecked it stays red. If you check the region again (3x) it turns a deeper red and the data export shows it as checked. This happens in the survey form and the Add/Edit Records when logged into REDCap.  I've tried all version of the PAINMAP_xx  and it still occurs.

**Comment by ChemiKyle** [comment] 2020-10-16 16:39
Thanks, I'm able to recreate your issue and I can see the cause. It's due to version differences so you could rollback your REDCap to make the module work ASAP, but I'm working on a fix.

**Comment by pbchase** [comment] 2020-10-20 20:45
Addressed in PR #54 and version 1.7.0.  The latter has be submitted to the REDCap Repo for review and publication.

**Closed by pbchase** 2020-10-20 20:45 UTC
